version: '3'
services:
  chaintest:
    image: anshooarora/chaintest:latest
    container_name: chaintest
    environment:
      - "SPRING_PROFILES_ACTIVE=postgres"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/chaintest
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - 80:80
